[phases.setup]
packages = ["nodejs_22_12"]

[phases.install]
commands = ["npm ci"]

[phases.build]
commands = ["npm run build"]

[start]
cmd = "node .output/server/index.mjs"

[env]
PORT = "3000"
NODE_ENV = "production"
