[phases.setup]
packages = ["nodejs_20", "npm"]

[phases.install]
commands = [
  "npm ci"
]

[phases.build]
commands = [
  "npm run build"
]

[phases.start]
cmd = "node .output/server/index.mjs"

[env]
PORT = "3000"
NODE_ENV = "production"
