[phases.setup]
packages = ["nodejs", "npm"]

[phases.install]
commands = [
    "npm install"
]

[phases.build]
commands = [
    "npm run build"
]

[phases.start]
commands = [
    "npm run start"
]

[env]
PORT = "3000"
NODE_ENV = "production"
