[phases.setup]
packages = ["nodejs_22"]

[phases.install]
commands = ["npm ci"]

[phases.build]
commands = ["npm run build"]

[phases.start]
commands = ["node .output/server/index.mjs"]

[env]
NODE_ENV = "production"
PORT = "3000"
